services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=GNANI1651A
      - MYSQL_DATABASE=springbootmvcsdpproject11
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "2028:2028"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springbootmvcsdpproject11
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=GNANI1651A